version: "3.8"
services:
  dynuiuc:
    container_name: dynuiuc
    image: regulad/docker-dynuiuc
    restart: unless-stopped
    environment:
      - USERNAME=email@example.com
      - PASSWORD=5KqnGY#d
      - LOCATION=Home
